#!/bin/bash

# toggle audio or video in chat applications

# (C) 2021 - 2023 Dan White
#
#
# Adding a new meeting tool:
#
#   Modify the three functions:
#       detect_chat_app
#       toggle_audio_keys
#       toggle_video_keys

set -euo pipefail

toggle_audio=0
toggle_video=0


help () {
    echo "$0: toggle microphone or video in chat applications"
    echo " -a   toggle audio/microphone mute (default)"
    echo " -v   toggle video/camera mute"
    exit 1
}



if [ "${1-}" = "" ]; then
    # no arguments?
    # default to toggle audio/mute state
    toggle_audio=1
fi

while [ -n "${1-}" ]; do
    case "$1" in
        -a|a) toggle_audio=1 ;;
        -v|v) toggle_video=1 ;;
        -h|--help) help ;;
        *) echo "Unrecognized argument: $1" ;;
    esac
    shift
done



detect_chat_app () {
    # Return a space-separated string of two fields:
    # <app-name-tag> <ID from xdotool>

    # Search by window title
    ZOOM=$(xdotool search --limit 1 --name "Zoom Meeting" \
           || xdotool search --limit 1 --name "Zoom for Government" || true)
    GOTOMEETING=$(xdotool search --limit 1 --name "GoTo" || true)
    JITSI=$(xdotool search --limit 1 --name "Jitsi Meet" || true)
    # First look for Jitsi
    MEET=$(xdotool search --limit 1 --name "Meet - " || true)


    if [ -n "$ZOOM" ]; then
        echo "zoom $ZOOM"
    elif [ -n "$GOTOMEETING" ]; then
        echo "gotomeeting $GOTOMEETING"
    elif [ -n "$JITSI" ]; then
        echo "jitsi $JITSI"
    # Google Meet needs to be low on this list
    elif [ -n "$MEET" ]; then
        echo "meet $MEET"
    else
        echo "none 0"
    fi
}


toggle_audio_keys () {
    APP=${1-none}

    case "$APP" in
        zoom) echo "alt+a" ;;
        gotomeeting) echo "alt+m" ;;
        jitsi) echo "m" ;;
        meet) echo "ctrl+d" ;;
        none|*) echo "" ;;
    esac
}


toggle_video_keys () {
    APP=${1-none}

    case "$APP" in
        zoom) echo "alt+v" ;;
        gotomeeting) echo "alt+v" ;;
        jitsi) echo "v" ;;
        meet) echo "ctrl+e" ;;
        none|*) echo "" ;;
    esac
}



declare -a APP=( $(detect_chat_app) )


if [ "${APP[0]}" = "none" ]; then
    echo "No detected chat app, exiting."
    exit 1
fi

echo "toggle audio: $toggle_audio"
echo "toggle video: $toggle_video"


if [ $toggle_audio -eq 1 -o $toggle_video -eq 1 ]; then
    CURRENT=$(xdotool getwindowfocus)

    xdotool windowactivate --sync ${APP[1]}

    if [ $toggle_audio -eq 1 ]; then
        xdotool key --clearmodifiers "$(toggle_audio_keys ${APP[0]})"
    fi

    if [ $toggle_video -eq 1 ]; then
        xdotool key --clearmodifiers "$(toggle_video_keys ${APP[0]})"
    fi

    xdotool windowactivate --sync ${CURRENT}
fi
